id: bottleneck_pipeline
namespace: company.bottleneck

description: |
  Pipeline industriel pour BottleNeck.
  Structure : 1 Script de Traitement -> 1 Script de Test (Fail-Fast).
  Inclus : Retries techniques et Alertes Mail en cas d'échec.

# --- PLANIFICATION ---
triggers:
  - id: monthly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 15 * *" 

tasks:
  - id: processing_zone
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      
      # 1. RÉCUPÉRATION DU CODE
      - id: git_clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/MarwaElAllouchi/bottleneck-project.git
        branch: main
        retry:
          type: constant 
          maxAttempts: 3 
          interval: PT30S 

      # 2. CHARGEMENT DES DONNÉES
      - id: 01_load_data
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/01_load_data.py
        retry:
          type: constant 
          maxAttempts: 2 
          interval: PT1M 

      # 3. NETTOYAGE
      - id: 02_clean_data
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/02_clean_data.py

      # 4. TEST QUALITÉ DONNÉES
      - id: test_quality_data
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/test_quality_data.py

      # 5. FUSION DES DONNÉES
      - id: 03_fusion_data
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/03_fusion_data.py

      # 6. TEST COHÉRENCE JOINTURE
      - id: test_coherence_jointure
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/test_coherence_jointure.py

      # 7. CALCUL DU CHIFFRE D'AFFAIRES
      - id: 04_calcul_ca
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/04_calcul_ca.py

      # 8. TEST COHÉRENCE MONTANT CA
      - id: test_coherence_ca
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/test_coherence_ca.py

      # 9. ANALYSE VINS PREMIUM
      - id: 05_vins_premium
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/05_vins_premium.py

      # 10. TEST STATISTIQUES ET EXPORT FINAL
      - id: test_statistiques_export
        type: io.kestra.plugin.scripts.python.Commands
        runner: DOCKER
        docker:
          image: python:3.11-slim
        beforeCommands:
          - pip install pandas numpy duckdb openpyxl
        commands:
          - python scripts/tests_statistiques_export.py

      # 11. RÉCUPÉRATION DES OUTPUTS
      - id: get_outputs
        type: io.kestra.plugin.core.storage.LocalFiles
        outputs:
          - exports/ca_par_produit.xlsx
          - exports/vins_premium.csv
          - exports/vins_ordinaires.csv

# --- GESTION DES ERREURS ---
errors:
  - id: alert_on_failure
    type: io.kestra.plugin.core.log.Log
    message: "❌ ALERTE : Le pipeline s'est arrêté. Une anomalie de donnée ou une erreur technique a été détectée."

  - id: send_test_email
    type: io.kestra.plugin.googleworkspace.mail.Send
    clientId: "{{ secret('GMAIL_CLIENT_ID') }}"
    clientSecret: "{{ secret('GMAIL_CLIENT_SECRET') }}"
    refreshToken: "{{ secret('GMAIL_REFRESH_TOKEN') }}"
    
    to:
      - "{{ secret('MAIL_ALERT') }}"
    subject: "🚨 Test Kestra - Pipeline BottleNeck {{ execution.id }}"
    htmlBody: |
     <h2>🚨 Alerte Pipeline BottleNeck</h2>
     <p>Le pipeline <b>BottleNeck</b> a rencontré une erreur lors de son exécution.</p>
     <p><b>Détails de l'exécution :</b></p>
      <ul>
        <li><b>ID de l'exécution :</b> {{ execution.id }}</li>
        <li><b>Date et heure :</b> {{ now() | date("dd/MM/yyyy HH:mm:ss") }}</li>
        <li><b>Étape :</b> {{ task.id }}</li> <!-- correction ici -->
        <li><b>Message :</b> Une anomalie de donnée ou une erreur technique a été détectée</li>
      </ul>
      <p>Veuillez consulter les logs Kestra pour plus de détails et résoudre le problème.</p>
      <p>Merci,</p>
      <p>L’équipe Data Engineering</p>